### ISSUE TITLE
Question about the initial update of the Broyden method

### ISSUE THREAD

**Issue by zaccharieramzi** [locuslab/mdeq#5]
Hi @jerrybai1995 ,

As you know I have been interested in the Broyden method you use in this code.
I have an implementation question regarding the intial update of the Broyden method that can be found [here](https://github.com/locuslab/mdeq/blob/master/lib/modules/broyden.py#L135).

Indeed, we have the following:
- each iteration for a given `update` direction is given in the code as more or less: `z = z + update` (see [here](https://github.com/locuslab/mdeq/blob/master/lib/modules/broyden.py#L93), where `s=1` because no line search is performed)
- this means that if `update` is `-gx`, then we have the first update being `z = z - gx`.

I think this is in contradiction with the suggested update in the paper, where we should have `z = z - B  gx = z - (-I) gx = z + gx`.

Of course this is very minor since it's just the initialization but I wanted to know your opinion on this given I am not sure how to resolve what I see as a contradiction.

**Comment by shaojieb** [comment]
Hi @zaccharieramzi ,

Good catch! Yes, that is indeed inconsistent... I'll look it up in the next few days. There are some delicate things in that algorithm that I should be especially careful about when debugging. Thanks so much for checking and pointing it out!!!

**Comment by shaojieb** [comment]
It seems that this can be easily fixed by changing the initial update from `-gx` to `gx` at this line: https://github.com/locuslab/mdeq/blob/master/lib/modules/broyden.py#L135

Essentially, although the `line_search` function is performing `z = z + update`,  because of [this line](https://github.com/locuslab/mdeq/blob/master/lib/modules/broyden.py#L177) (notice the negative sign especially), the approximation of Jacobian we are using is still essentially $J^{-1} \approx B = -I + UV^T$. Thus initially, we should have $B=-I$, which means the initial update should be `gx` rather than `-gx` indeed. 

Let me know if that clarifies the issue! I'm currently re-running some experiments to make sure I didn't break anything accidentally; if things work out well, I'll update the repo on this initialization change.

Thanks again for spotting this!

**Comment by zaccharieramzi** [comment]
Yes definitely the fix is easy, and as I said you probably didn't break anything because it's just the init. But you might end up being slightly faster haha!

**Comment by shaojieb** [comment]
This is now updated in the repo. Thanks for the tip!

**Comment by zaccharieramzi** [comment]
cool! Did it change anything substantially in terms of convergence speed?

**Comment by shaojieb** [comment]
I think it saved things by 1 iteration (and the original DEQ-Transformer repo was already using the right initialization, so that was not affected at all), so not quite substantial :D
