### ISSUE TITLE
out of memory at validation stage

### ISSUE THREAD

**Issue by ShoufaChen** [locuslab/mdeq#9]
Hi,

Thanks for your code.

I encountered `RuntimeError: CUDA out of memory. Tried to allocate 25.49 GiB (GPU 0; 23.70 GiB total capacity; 57.77 MiB already allocated; 22.24 GiB free; 84.00 MiB reserved in total by PyTorch)` at eval stage with 24G memory.
```
python tools/cls_train.py --cfg experiments/cifar/cls_mdeq_TINY.yaml
```

**Comment by shaojieb** [comment]
Hi @ShoufaChen ,

I'm not sure if it's the problem of the repo. According to the error, there are still 22.24GB memory free on your GPU. This Tiny task should only consume hundreds of MB of GPU memory at most. Are you sharing the same GPU with other person/tasks?

**Comment by ShoufaChen** [comment]
No sharing.

I think it's strange. Traing is OK but val is OOM at the first epoch.

Thanks for your reply. I'll check it again.

**Comment by shaojieb** [comment]
Yeah strange indeed, and it's hard for me to imagine a 170K-sized model on a dataset as small as CIFAR would be so "memory-consuming"... Let me know if you find the issue!

**Comment by ShoufaChen** [comment]
Hi,

I'm sorry I can's find the issue now. Only evaluation is OK. It seems OOM happens when switching mode between train and evaluation.

**Comment by shaojieb** [comment]
Sorry to hear that. It's weird indeed... and you are definitely the first person I know that runs into this issue. 

Some potentially useful things that may help you locate the issue:
  - If you are using an IDE like PyCharm or VSCode, maybe you can set breakpoint and trace what exactly causes the memory to explode.
  - What version of PyTorch and Python are you using? I just cloned the repo and tried, and it seemed to work as usual. I'm using PyTorch 1.8.0 (with CUDA 11.0) and Python 3.6. Maybe creating a separate conda environment to debug this will be helpful.
  - If you simply "skip" the validation phase after the first epoch's training, and go to the next training epoch, does OOM occur? Because in the perspective of the program, they should be doing quite similar things (other than model.eval() vs. model.train()).

**Comment by ShoufaChen** [comment]
Thanks very much for your kind reply.

* I'm not using any IDE.  I use `pdb` for debugging and find this happened at the model forward in validation.
* I'm using the newest pytorch1.8.1 from pytorch official webset. `py3.8_cuda11.1_cudnn8.0.5_0`
* If I skip validation, ~~I can successfully go to the next training epoch, without OOM.~~   The **OOM** happened at the 3rd epoch, while the first two epochs run smoothly.

**Comment by ShoufaChen** [comment]
I think this is an environment-related issue. Please feel free to ignore it if your bandwidth is limited, as there is no one else who runs into the same issue.

Thank you all the way.

**Comment by shaojieb** [comment]
I'm closing this issue for now but please feel free to re-open and let me know if you still cannot identify the problem! (And sorry, I'm indeed a bit occupied recently.)
